create table Cliente(
    cod number(6) CONSTRAINT PK_COD_CLIENTE primary key,
    nome varchar(30),
    ativo number(2) DEFAULT 1,
    data_nasc date
);

/*DROP TABLE CLIENTE;*/

select CONSTRAINT_NAME, CONSTRAINT_TYPE, STATUS, SEARCH_CONDITION
from USER_CONSTRAINTS
where TABLE_NAME = 'CLIENTE';

CREATE TABLE PEDIDO (
    PED_COD NUMBER(6),
    PED_DATA DATE,
    PED_VALOR NUMBER(7,2),
    CONSTRAINT PEDIDO_PK PRIMARY KEY(PED_COD)
);

CREATE TABLE PRODUTO (
    PROD_COD NUMBER(6),
    PROD_NOME VARCHAR(20),
    CONSTRAINT PRODUTO_PK PRIMARY KEY(PROD_COD)
);

CREATE TABLE ITEMPEDIDO (
    PED_COD NUMBER(6) CONSTRAINT IP_PED_FK REFERENCES PEDIDO(PED_COD),
    PRO_COD NUMBER(6) CONSTRAINT IP_PROD_FK REFERENCES PRODUTO(PROD_COD),
    ITE_QTD NUMBER(6),
    ITE_VALOR NUMBER(7,2),
    CONSTRAINT IP_PK PRIMARY KEY(PED_COD, PRO_COD)
);

INSERT INTO PEDIDO(PED_COD, PED_DATA, PED_VALOR) VALUES(1,TO_DATE('10-02-2020','DD-MM-YYYY'),353.58);
SELECT * FROM PEDIDO;