ALTER TABLE PROJETO ADD PRO_STATUS NUMBER(1) NOT NULL CONSTRAINT CK_PROJETO_PRO_STATUS CHECK(PRO_STATUS IN(0,1));

ALTER TABLE PROJETO MODIFY PRO_TITULO VARCHAR2(252);

ALTER TABLE PROJETO RENAME COLUMN PRO_DATA_CAD TO PRO_DATA_CADASTRO;

DESC PROJETO;


CREATE TABLE ENDERECO(
    END_COD NUMBER(4) CONSTRAINT PK_ENDERECO PRIMARY KEY,
    END_ENDERECO VARCHAR2(252)
);


CREATE TABLE ENDERECO_FUNCIONARIO(
    ENF_COD_FUNC NUMBER(4) CONSTRAINT FK_ENF_FUNCIONARIO REFERENCES FUNCIONARIO(FUN_COD_FUNC),
    ENF_COD_END NUMBER(4) CONSTRAINT FK_ENF_ENDERECO REFERENCES ENDERECO(END_COD),
    CONSTRAINT PK_ENDERECO_FUNCIONARIO PRIMARY KEY(ENF_COD_FUNC, ENF_COD_END)
);


ALTER TABLE FUNCIONARIO DROP COLUMN FUN_ENDERECO;

ALTER TABLE FUNCIONARIO DROP CONSTRAINT CK_FUNCIONARIO_FUN_SALARIO;

ALTER TABLE FUNCIONARIO DISABLE CONSTRAINT UK_FUNCIONARIO;
ALTER TABLE FUNCIONARIO ENABLE CONSTRAINT UK_FUNCIONARIO;

ALTER TABLE FUNCIONARIO DISABLE CONSTRAINT PK_FUNCIONARIO;
ALTER TABLE FUNCIONARIO ENABLE CONSTRAINT PK_FUNCIONARIO;

DESC FUNCIONARIO;


CREATE TABLE PARENTESCO(
    PAR_COD NUMBER(4) CONSTRAINT PK_PARENTESCO_PAR_COD PRIMARY KEY,
    PAR_DESCR VARCHAR2(30)
);

ALTER TABLE DEPENDENTE DROP CONSTRAINT CK_DEPE_PARENTESCO;
ALTER TABLE DEPENDENTE MODIFY DEPE_PARENTESCO NUMBER(4);
ALTER TABLE DEPENDENTE ADD CONSTRAINT FK_DEPENDENTE_PARENTESCO FOREIGN KEY(DEPE_PARENTESCO) REFERENCES PARENTESCO(PAR_COD);

ALTER TABLE DEPENDENTE ADD DEPE_CPF VARCHAR2(15) CONSTRAINT UK_DEPE_CPF UNIQUE;

ALTER TABLE DEPENDENTE DROP CONSTRAINT FK_DEPENDENTE_FUNCIONARIO;
ALTER TABLE DEPENDENTE ADD CONSTRAINT FK_DEPENDENTE_FUNCIONARIO FOREIGN KEY(DEPE_COD_FUNC)
REFERENCES FUNCIONARIO(FUN_COD_FUNC) ON DELETE CASCADE;

DESC DEPENDENTE;


ALTER TABLE PARTICIPA RENAME TO FUNC_PROJETO;

DESC FUNC_PROJETO;