CREATE TABLESPACE TS_P3
DATAFILE 'D:\Docs\Fatec\Programacao_de_Banco_de_Dados\Pratica3\TS_P3.dbf' SIZE 1M 
AUTOEXTEND ON;

CREATE USER USER_TS_P3
IDENTIFIED BY aluno
DEFAULT TABLESPACE TS_P3
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON TS_P3;

GRANT DBA TO USER_TS_P3 WITH ADMIN OPTION;