CREATE TABLESPACE TS_P3
DATAFILE 'C:\BD\TS_P3.dbf' SIZE 1M 
AUTOEXTEND ON;

CREATE USER USER_TS_P3
IDENTIFIED BY aluno
DEFAULT TABLESPACE TS_P3
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON TS_P3;

GRANT DBA TO USER_TS_P3 WITH ADMIN OPTION;