CREATE TABLESPACE  TS_BD
DATAFILE  '/mnt/14F60716F606F82E/Docs/Fatec/Programacao_de_Banco_de_Dados/BD/TS_BD_LINUX.dbf' SIZE 1M 
AUTOEXTEND ON;

CREATE USER USER_BD
IDENTIFIED BY ALUNO 
DEFAULT TABLESPACE TS_BD
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON TS_BD;

GRANT DBA TO USER_BD WITH ADMIN OPTION;
