CREATE TABLE FUNCIONARIO(
    FUN_COD_FUNC NUMBER(4),
    FUN_NOME VARCHAR2(100) NOT NULL,
    FUN_CPF VARCHAR2(15),
    FUN_SALARIO NUMBER(4,2),
    FUN_ENDERECO VARCHAR2(252),
    FUN_SEXO CHAR(1),
    FUN_COD_SUPER NUMBER(4),
    FUN_COD_DEPART NUMBER(4),
    CONSTRAINT PK_FUNCIONARIO PRIMARY KEY(FUN_COD_FUNC),
    CONSTRAINT UK_FUNCIONARIO UNIQUE(FUN_CPF),
    CONSTRAINT CK_FUNCIONARIO_FUN_SALARIO CHECK(FUN_SALARIO >= 1000),
    CONSTRAINT CK_FUNCIONARIO_FUN_SEXO CHECK(FUN_SEXO IN('F','M')),
    CONSTRAINT FK_FUNCIONARIO_FUNCIONARIO FOREIGN KEY(FUN_COD_SUPER) REFERENCES FUNCIONARIO(FUN_COD_FUNC)
);


CREATE TABLE DEPARTAMENTO(
    DEP_COD_DEPART NUMBER(4) CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY,
    DEP_NOME VARCHAR2(30) NOT NULL,
    DEP_DATA_INICIAL DATE
);


ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK_FUN_COD_DEPART FOREIGN KEY(FUN_COD_DEPART) REFERENCES DEPARTAMENTO(DEP_COD_DEPART);


CREATE TABLE LOCALIZACAO(
    LOC_COD_DEPART NUMBER(4) CONSTRAINT FK_LOC_COD_DEPART REFERENCES DEPARTAMENTO(DEP_COD_DEPART),
    LOC_LOCAL VARCHAR2(252),
    CONSTRAINT PK_LOCALIZACAO PRIMARY KEY(LOC_COD_DEPART, LOC_LOCAL)
);


CREATE TABLE DEPENDENTE(
    DEPE_COD_FUNC NUMBER(4) CONSTRAINT FK_DEPENDENTE_FUNCIONARIO REFERENCES FUNCIONARIO(FUN_COD_FUNC),
    DEPE_SEQ NUMBER(4),
    DEPE_NOME VARCHAR2(100) NOT NULL,
    DEPE_PARENTESCO VARCHAR2(30) NOT NULL CONSTRAINT CK_DEPE_PARENTESCO CHECK(DEPE_PARENTESCO IN ('PAI','MAE','IRMAOS','FILHO')),
    DEPE_DATA_NASC DATE,
    CONSTRAINT PK_DEPENDENTE PRIMARY KEY(DEPE_COD_FUNC, DEPE_SEQ)
);


CREATE TABLE PROJETO(
    PRO_COD_PROJ NUMBER(4) CONSTRAINT PK_PROJETO PRIMARY KEY,
    PRO_COD_DEPART NUMBER(4) CONSTRAINT FK_PROJETO_DEPARTAMENTO REFERENCES DEPARTAMENTO(DEP_COD_DEPART),
    PRO_TITULO VARCHAR2(150) NOT NULL,
    PRO_DESCRICAO VARCHAR2(252),
    PRO_DATA_CAD DATE DEFAULT SYSDATE
);


CREATE TABLE PARTICIPA(
    PAR_COD_FUNC NUMBER(4) CONSTRAINT FK_PARTICIPA_FUNCIONARIO REFERENCES FUNCIONARIO(FUN_COD_FUNC),
    PAR_COD_PROJ NUMBER(4) CONSTRAINT FK_PARTICIPA_PROJETO REFERENCES PROJETO(PRO_COD_PROJ),
    PAR_HORAS VARCHAR2(50),
    CONSTRAINT PK_PARTICIPA PRIMARY KEY(PAR_COD_FUNC, PAR_COD_PROJ)
);


SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, STATUS, SEARCH_CONDITION
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'PARTICIPA';